name: Release Versioned Tarball

on:
  push:
    tags:
    - '*' # Push events of any tag created

jobs:
  build_tarball:
    name: Upload Release Tarball
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump Djinn Version
        run: |
          sed -i "s/0\.0\.0/${{ github.ref_name }}/g" djinn/__main__.py
          sed -i "s/0\.0\.0/${{ github.ref_name }}/g" pyproject.toml         
      - name: Build project
        # This builds the release tarball, stripped of unneccessary things
        run: |
          mkdir artifacts
          tar --exclude="test" --exclude=".deprecated" --exclude="resources" --exclude="artifacts" --exclude=".git" --exclude=".github" -zcvf artifacts/djinn.${{ github.ref_name }}.tar.gz .
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/djinn.${{ github.ref_name }}.tar.gz
